const KEY='dh-recipes-v1', SHOP='dh-shop-v1';
const seed=[{id:crypto.randomUUID(),name:'Garlic Sourdough',category:'Sides',serves:4,fav:true,ingredients:['4 thick slices sourdough','3 tbsp olive oil','2 tsp chopped garlic','Pinch of salt','Black pepper'],method:['Heat the oven to 200°C.','Mix the olive oil, garlic, salt and pepper.','Brush generously over the sourdough.','Bake for 8–10 minutes until crisp at the edges.'],},{id:crypto.randomUUID(),name:'Chorizo Tomato Pasta',category:'Pasta',serves:4,fav:false,ingredients:['300–350g pasta','100–150g chorizo, diced','1 tin chopped tomatoes','2 tsp chopped garlic','1 tsp mixed herbs','1 tsp balsamic vinegar','Cheddar, to finish'],method:['Cook the pasta in salted water.','Fry the chorizo until it releases its oils.','Add garlic, then tomatoes, herbs and balsamic vinegar.','Simmer for 10–15 minutes.','Toss through the pasta and finish with grated cheddar.']}];
let recipes=JSON.parse(localStorage.getItem(KEY)||'null')||seed, view='recipes', cat='All';
const $=s=>document.querySelector(s), recipesEl=$('#recipes'), shopping=$('#shopping');
function save(){localStorage.setItem(KEY,JSON.stringify(recipes))} save();
function categories(){return ['All',...new Set(recipes.map(r=>r.category).filter(Boolean))]}
function render(){ const q=$('#search').value.toLowerCase(); $('#cats').innerHTML=categories().map(c=>`<button class="${c===cat?'active':''}" data-cat="${c}">${c}</button>`).join('');
let list=recipes.filter(r=>(view!=='favs'||r.fav)&&(cat==='All'||r.category===cat)&&(`${r.name} ${r.ingredients.join(' ')}`.toLowerCase().includes(q))); recipesEl.innerHTML=list.map(r=>`<div class="card" data-id="${r.id}"><button class="heart" data-heart="${r.id}">${r.fav?'♥':'♡'}</button><div><small>${esc(r.category||'Recipe')}</small><h3>${esc(r.name)}</h3></div><div class="meta">Serves ${r.serves||'—'} · ${r.ingredients.length} ingredients</div></div>`).join('')||'<p>No recipes found.</p>'; recipesEl.classList.toggle('hidden',view==='shopping'); shopping.classList.toggle('hidden',view!=='shopping'); if(view==='shopping') renderShop();}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function openForm(r){$('#formTitle').textContent=r?'Edit Recipe':'Add Recipe'; $('#rid').value=r?.id||''; $('#name').value=r?.name||''; $('#category').value=r?.category||''; $('#serves').value=r?.serves||4; $('#ingredients').value=r?.ingredients.join('\n')||''; $('#method').value=r?.method.join('\n')||''; $('#modal').showModal()}
function detail(r){$('#detailBody').innerHTML=`<div class="detailTop"><button onclick="detail.close()">✕</button><button onclick="toggleFav('${r.id}')">${r.fav?'♥':'♡'}</button></div><small>${esc(r.category)}</small><h1>${esc(r.name)}</h1><p>Serves ${r.serves}</p><div class="actions"><button onclick="addShop('${r.id}')">Add ingredients</button><button class="secondary" onclick="editRecipe('${r.id}')">Edit</button></div><h2>Ingredients</h2><ul class="ingredients">${r.ingredients.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h2>Method</h2><ol class="steps">${r.method.map(x=>`<li>${esc(x)}</li>`).join('')}</ol><div class="actions"><button class="secondary" onclick="deleteRecipe('${r.id}')">Delete recipe</button></div>`; $('#detail').showModal()}
window.toggleFav=id=>{let r=recipes.find(x=>x.id===id);r.fav=!r.fav;save();render();if($('#detail').open)detail(r)}; window.editRecipe=id=>{let r=recipes.find(x=>x.id===id);$('#detail').close();openForm(r)}; window.deleteRecipe=id=>{if(confirm('Delete this recipe?')){recipes=recipes.filter(x=>x.id!==id);save();$('#detail').close();render()}};
window.addShop=id=>{let r=recipes.find(x=>x.id===id), items=JSON.parse(localStorage.getItem(SHOP)||'[]');items.push(...r.ingredients.map(text=>({text,done:false})));localStorage.setItem(SHOP,JSON.stringify(items));alert('Ingredients added to your shopping list.')};
function renderShop(){let items=JSON.parse(localStorage.getItem(SHOP)||'[]');$('#shopItems').innerHTML=items.length?items.map((x,i)=>`<label class="shoprow"><input type="checkbox" data-shop="${i}" ${x.done?'checked':''}><span>${esc(x.text)}</span></label>`).join(''):'<p>Your shopping list is empty.</p>'}
$('#recipeForm').onsubmit=e=>{e.preventDefault();let id=$('#rid').value||crypto.randomUUID(), old=recipes.find(r=>r.id===id);let r={id,name:$('#name').value.trim(),category:$('#category').value.trim()||'Other',serves:+$('#serves').value||1,fav:old?.fav||false,ingredients:$('#ingredients').value.split('\n').map(x=>x.trim()).filter(Boolean),method:$('#method').value.split('\n').map(x=>x.trim()).filter(Boolean)};recipes=old?recipes.map(x=>x.id===id?r:x):[r,...recipes];save();$('#modal').close();render()};
$('#cancel').onclick=()=>$('#modal').close(); $('#addTop').onclick=$('#addNav').onclick=()=>openForm(); $('#search').oninput=render; $('#cats').onclick=e=>{if(e.target.dataset.cat){cat=e.target.dataset.cat;render()}}; recipesEl.onclick=e=>{let h=e.target.dataset.heart;if(h){e.stopPropagation();toggleFav(h);return}let c=e.target.closest('.card');if(c)detail(recipes.find(r=>r.id===c.dataset.id))};
document.querySelector('nav').onclick=e=>{let b=e.target.closest('[data-view]');if(!b)return;view=b.dataset.view;document.querySelectorAll('nav [data-view]').forEach(x=>x.classList.toggle('active',x===b));render()}; $('#clearShop').onclick=()=>{localStorage.removeItem(SHOP);renderShop()}; $('#shopItems').onchange=e=>{if(e.target.dataset.shop!==undefined){let a=JSON.parse(localStorage.getItem(SHOP)||'[]');a[+e.target.dataset.shop].done=e.target.checked;localStorage.setItem(SHOP,JSON.stringify(a))}};render();
